### ISSUE TITLE
Otherscape macros missing from current version

### ISSUE THREAD

**Issue by WisdomOfWombats** [mordachai/mist-hud#2]
The macro compendium only contains the CoM macros, but not the Otherscape macros - though those are visible in the screenshot in the CoM discord on foundry.

https://cdn.discordapp.com/attachments/834505065250160660/1304561556486357052/image.png?ex=6731d160&is=67307fe0&hm=21a9ecf2a25ebb73921bc35e5d0dee540fa5cb557ddaad5c6311d908385c4345&

**Comment by mordachai** [comment]
my, bad, forgot to update. all good now!
